export // USER
const SET_USER = "SET_USER",
  GET_USER = "GET_USER",
  REGISTER_USER = "REGISTER_USER",
  LOGIN_USER = "LOGIN_USER",
  LOGOUT_USER = "LOGOUT_USER",
  UPDATE_USER_DETAIL = "UPDATE_USER_DETAIL",
  UPDATE_USER_SECURITY = "UPDATE_USER_SECURITY",
  // PROJECT
  CREATE_PROJECT = "CREATE_PROJECT",
  SUBMIT_PROJECT = "SUBMIT_PROJECT",
  ALL_PROJECTS = "ALL_PROJECTS",
  //INVECTMENT
  CREATE_INVESTMENT = "CREATE_INVESTMENT",
  SUBMIT_INVESTMENT = "SUBMIT_INVESTMENT",
  ALL_INVESTMENTS = "ALL_INVESTMENTS",
  // STRIPE
  ALL_CARDS = "ALL_CARDS",
  ADD_CARD = "ADD_CARD",
  DELETE_CARD = "DELETE_CARD";
