export // USER
const SET_USER = "SET_USER",
  LOGOUT_USER = "LOGOUT_USER",
  UPDATE_USER_DETAIL = "UPDATE_USER_DETAIL",
  UPDATE_USER_SECURITY = "UPDATE_USER_SECURITY",
  UPDATE_USER_IMAGE = "UPDATE_USER_IMAGE",
  // PROJECT
  CREATE_PROJECT = "CREATE_PROJECT",
  CREATE_PROJECT_DRAFT = "CREATE_PROJECT_DRAFT",
  ALL_PROJECTS = "ALL_PROJECTS",
  GET_PROJECT = "GET_PROJECT",
  UPDATE_PROJECT_IMAGE = "UPDATE_PROJECT_IMAGE",
  ALL_USER_PROJECTS = "ALL_USER_PROJECTS",
  //FAVORITE
  TOGGLE_FAVORITE_PROJECT = "TOGGLE_FAVORITE_PROJECT",
  FAVORITE_PROJECTS = "FAVORITES_PROJECTS",
  //INVESTMENT
  CREATE_INVESTMENT = "CREATE_INVESTMENT",
  SUBMIT_INVESTMENT = "SUBMIT_INVESTMENT",
  ALL_USER_INVESTMENTS = "ALL_INVESTMENTS",
  SET_INVESTMENT_AMOUNT = "SET_INVESTMENT_AMOUNT",
  SET_PAYMENT_METHOD = "SET_PAYMENT_METHOD",
  FIND_PROJECT_INVESTMENT = "FIND_PROJECT_INVESTMENT",
  SUCCESSFUL_INVESTMENT = "SUCCESSFUL_INVESTMENT",
  GET_INVESTMENT = "GET_INVESTMENT",
  // STRIPE
  ALL_CARDS = "ALL_CARDS",
  ADD_CARD = "ADD_CARD",
  DELETE_CARD = "DELETE_CARD",
  CREATE_PAYMENT_INTENT = "CREATE_PAYMENT_INTENT",
  ADD_LINK = "ADD_LINK",
  GET_ACCOUNT = "GET_ACCOUNT",
  // ALERT
  SET_ALERT = "SET_ALERT",
  // LOADING
  SET_LOADING_REGISTER = "SET_LOADING_REGISTER",
  SET_LOADING_LOGIN = "SET_LOADING_LOGIN",
  //COMMENT
  CREATE_COMMENT = "CREATE_COMMENT",
  DELETE_COMMENT = "DELETE_COMMENT",
  GET_ALL_COMMENTS = "GET_ALL_COMMENTS",
  // LAYOUT
  SET_WINDOW_WIDTH = "SET_WINDOW_WIDTH",
  // SOCKET
  SET_SOCKET = "SET_SOCKET";
