export // USER
const SET_USER = "SET_USER",
  GET_USER = "GET_USER",
  REGISTER_USER = "REGISTER_USER",
  LOGIN_USER = "LOGIN_USER",
  LOGOUT_USER = "LOGOUT_USER",
  // PROJECT
  CREATE_PROJECT = "CREATE_PROJECT",
  SUBMIT_PROJECT = "SUBMIT_PROJECT";
